services:
  mongo_db:
    image: mongo:latest
    container_name: library_mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: library_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: book-cache
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: library_api_fastapi
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MONGO_URL=mongodb://mongo_admin:password123@mongo_db:27017
      - REDIS_URL=redis://redis:6379/0
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - mongo_db
      - redis

volumes:
  mongo_data: