services:
  mongo_db:
    image: mongo:latest
    container_name: library_mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: library_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web:
    build: .
    container_name: library_api_flask
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MONGO_URL=mongodb://mongo_admin:password123@mongo_db:27017
    # Flask за замовчуванням стартує на 5000 порту, але ми прокинемо його на 8000, щоб не міняти порти
    command: python main.py
    depends_on:
      - mongo_db

volumes:
  mongo_data: