version: '3.8'

services:
  # Наш новий mock-сервер Prism
  mock-api:
    image: stoplight/prism:5
    container_name: library_prism_mock
    ports:
      - "4010:4010"
    volumes:
      - ./openapi.yaml:/openapi.yaml:ro
    # Додали прапорець --multiprocess=false в кінець команди
    command: mock -h 0.0.0.0 -p 4010 /openapi.yaml --multiprocess=false
    restart: always

  # Твої попередні сервіси (FastAPI, MongoDB, Redis) можна залишити нижче, 
  # але для ЛР8 нам потрібен саме цей mock-api сервіс.